language: java
sudo: required
services:
- docker
jdk:
- oraclejdk8
script: ".travis/build.sh"
cache:
  directories:
  - "$HOME/.m2"
install: true
env:
  global:
  - DOCKER_USER: yervand
  - secure: F/wRxoUULWWRslnhJoYDYkmtmCQAK7CheSII/ZP/88x+8n2Zb95p8NrnKCev3QZR9TeswZRPEMERfeyYEdZbjlFRRN1p8ZqKPzrq0EZYUhPdmps3kOl97cl9RMi/mxxDgALKdv9ebsNU7/fAGYkEhrKZ6mUAs2/LoBUxm8fJBXJ3JQrN4qhcqnFJHDg98DtszRz+79uXwVsv2a366iQJUH8K9OJJdixnTGczx36ISumcnDZYUCt3Gi9sZMpZUhIKvzVq4CCIY0wKtymq6eD0j0dWMcTn1fXqqVt8VLaQ3syoxo9iAEcPeXSynbuegn+ZPRPJZh4CMeGEFwI5lCxHa6DN/x8/1o56ZoLuf13NtIt0pySDlXmlk/WFKyorwuTgY2XpX/14yBJZrd4cW6PYqPlo6viCMzH8JdL4a6vpWWXZqfZnb3fpbzuUe/P69U+49s/xcRUFYxQRhlAWlui/hXAtTy43LpQGmwmbud3RbZTDctHqbAthvB+xsT4FXr+BDCEB7llfW6VqhidUzSYns3Knqkgi97CTLgrrisWp1Ul+mBLqt8oXyECuGE1KbvwGRT21o6SVkUTdFuCnwp0JvXHGY3jgyKaCGdBTGJBIx4T3E2qRLBJlLbei7lKOfsE3to76VZtZKtF9JAJ3sPQ58Zrigyz/q6K91R3A9UePeQ8=
  - secure: f3GleIsJJpn2dSrh1uCwGtxg+D7zUygKYbwuO20Pl+rQS704fgA+x5pOoz820bLN+CZxbJI7AY2AySwLEMhWozfA9QW85RJO7kKakJekct2W5zbTdm0Crb1uQ4iNVc64V6BJhdtHOx5jkK9EIzjkRhvoOKbamCTGwrVkg3bKJcOD31V5MlNRoXvUT/Nr22whDzTLKJ4pavP0LbzEGSnHwUXcrI7IBIkNNqyOXMqB+j4jnU7WhpP8KL0UzAC4S0CQ6+f2hROV+spraSI6tp5CtHdAmTo+nM3gxkXopaVic8WRoTn7UrgLOoWB4d9nBVoOxwaw6tOtPlAVTV+n7FsosG/ThY53ScA94NiAPyqRsD18IXcOykNNtxhRaSshj/jJ2v6A0AG24fxedQ+Y56s5bmPVNbqe136lhva20Vs9Xk0PswWyRLGrM7jcSsI9qOa1Bzyd9DmpRz7enmrKNl49Wu6Wwsd7hlaacxFUBmD8sLA9miMKUEybpFhya0+jRvO1Hh8qyxbO/M6XaJIhJfPGrjsc0SDjdcUb5fadkbnUhaN3xOoSKdC1r4RCpHuV/4TPqrELHqOkj6hjjf/5XDSabbrdiPC+wrtERJMlDl4W4wdFPGfpKRpTQ/uDdPRKMO5bFwxR0BRcIC4o9ggChiWdOx3Jy4jTnkQ7aJNQ2y74HuU=
  - secure: HTlv4tRDnEM1NdXnaNsTPpelcJEYdfJPyvc+rgiz4QDIf7FrReuOJEoZ7Lq5hkhyT58VAc6wXUQXkfqDhKFCyqlrE30T/ooFlyCt9ucJE42OW/qi7YiHKtvxW5iXHkWty1Ad0xFnIUZWq3Ww8Fbv489SwmymZ7FinY7r0vhqNWRdCLhjo7P1mIT0v/1uHP6wWGZWqBfzrQ0bfKKJJ+crt4Ml3XyuwyrY0BXGeu87oPZoL0QQuTbYguxULynMKqGBGGORSHMCpBTtBNRX4PCvS8B77mcsSIvpXjFWDyqk5NIurTO6epUNXxlUynm/Sl4fpSROkBBawCMxycaN2fTBcMaAKy13rBafpx/S6JyI2Uh4twYSbEQPBi0lkPuJ2LTvIJaxsdL2CGx350ixPvzcHF56myifukVuXxe/WMj8hVZRC0tYdot8aTcgodusoaJ9yesc/AvDpzQHcTeMa/LJB8Do7Trw4iJ+BBX+RGGydI+NjFvr/9Eur3HHkgcCOPYkI5KS9XnT3jS8AZU8/8MvqVM4qOFGqTtDrbrpBKWV0qZcF0KtuP+meawtbNudPEliaU1JdBokzmRFd5itXeW/986nG0IhrGeLWcjTNrxXTgG4HUMBGPsCDD0GISOfc/cj+4aImi9B9xlMjr7aG+mRdNLE6nmZIBH2aWEST4VyaWY=
before_script:
- openssl aes-256-cbc -K $encrypted_49fa1606db88_key -iv $encrypted_49fa1606db88_iv
  -in travis-gpg-key.asc.enc -out travis-gpg-key.asc -d
